export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_WEATHER_FORECAST_SUCCESS = 'FETCH_WEATHER_FORECAST_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';

export const SET_SEARCH_FOCUS = 'SET_SEARCH_FOCUS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const CHANGE_TEMPERATURE = 'CHANGE_TEMPERATURE';